// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoqztlogrqobxtwljvjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvcXp0bG9ncnFvYnh0d2xqdmp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MjU1OTQsImV4cCI6MjA2NjMwMTU5NH0.DxNS8q7CMPSFjme5uto5VwjxFVM5s84LNpgNsDIIwGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);